### ISSUE TITLE
TypeError thrown when computing completion items at the end of a `COPY` instruction with flags

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-server-nodejs#258]
```TypeScript
import { DockerfileLanguageServiceFactory } from "dockerfile-language-service";
const service = DockerfileLanguageServiceFactory.createLanguageService();
service.computeCompletionItems("COPY --from=a ", { line: 0, character: 14 });
```
```
$ node test.js
../dockerfile-language-service/out/src/dockerAssist.js:354
        const lastRange = args[args.length - 1].getRange();
                                                ^

TypeError: Cannot read properties of undefined (reading 'getRange')
    at DockerAssist.createTargetFolderProposals (../dockerfile-language-service/out/src/dockerAssist.js:354:49)
    at DockerAssist.createCopyProposals (../dockerfile-language-service/out/src/dockerAssist.js:344:21)
    at DockerAssist.computeProposals (../dockerfile-language-service/out/src/dockerAssist.js:174:37)
    at LanguageService.computeCompletionItems (../dockerfile-language-service/out/src/languageService.js:56:29)
    at Object.<anonymous> (../dockerfile-language-service/out/src/tmp.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

**Comment by rcjsuen** [comment]
Whoops. Meant to open this in the language service repository as https://github.com/rcjsuen/dockerfile-language-service/issues/97.
