### ISSUE TITLE
Dockerls crashes immediately on opening dockerfiles

### ISSUE THREAD

**Issue by nwithers-ecr** [rcjsuen/dockerfile-language-server-nodejs#260]
I am using the built-in nvim lspconfig
The client crashes with `Client 1 quit with exit code 1 and signal 0` even if the file is empty. 
# $HOME/.cache/nvim/lsp.log
```
[START][2021-12-10 10:25:43] LSP logging initiated
[ERROR][2021-12-10 10:25:43] .../vim/lsp/rpc.lua:412    "rpc"   "/home/nwithers/.local/share/nvim/lsp_servers/dockerfile/node_modules/.bin/docker-langserver"   "stderr"        "/home/nwithers/.local/share/nvim/lsp_servers/dockerfile/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nwithers/.local/share/nvim/lsp_servers/dockerfile/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
"
```

**Comment by rcjsuen** [comment]
@nwithers-ecr Thank you for the bug report.

What version of Node.js do you have installed? Could you share the output of `node -v` from the command line? Thanks.

**Comment by nwithers-ecr** [comment]
@rcjsuen I currently have `v10.19.0` installed

**Comment by rcjsuen** [comment]
> I currently have `v10.19.0` installed

@nwithers-ecr Thanks for the information.

1. The Node.js 10.x series reached end-of-life in April 2022.
2. The current LTS is the 16.x series so I suggest you upgrade to that.

**Comment by nwithers-ecr** [comment]
ah.. it appears I am behind the times. I installed v17.2.0 and I see no errors. Sorry for the noise.

**Comment by rcjsuen** [comment]
> ah.. it appears I am behind the times. I installed v17.2.0 and I see no errors. Sorry for the noise.

No big deal. Have a nice day!
