### ISSUE TITLE
Server cannot launch, fails with a Syntax Error

### ISSUE THREAD

**Issue by klnusbaum** [rcjsuen/dockerfile-language-server-nodejs#262]
I tried to run the following command. I would expect it to start up the language server, but instead I'm seeing a syntax error:

```
2022-12-19 01:18:36 UTC kurtis@kdevenv # docker-langserver --stdio                     
/usr/local/lib/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
2022-12-19 01:18:50 UTC kurtis@kdevenv # docker-langserver --help 
/usr/local/lib/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/linkedMap.js:40
        return this._head?.value;
                          ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dockerfile-language-server-nodejs/node_modules/vscode-jsonrpc/lib/common/api.js:37:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
   ```
   
   This is on Debian Bullseye. I installed the server with:
```
npm install -g dockerfile-language-server-nodejs@0.0.24
```
Node version:
```
2022-12-19 05:09:15 UTC kurtis@kdevenv # node --version
v12.22.12
```

**Comment by klnusbaum** [comment]
nvm, looks like my version of node is ancient.
